name = "HB Starter Theme Template"
license = "MIT"
licenselink = "https://github.com/ronibd0/bdmeter.info/blob/main/LICENSE"
description = "The starter theme template of HB (Hugo Bootstrap) Framework"
homepage = "https://github.com/ronibd0/bdmeter.info"
demosite = "https://bdmeter.info/"
tags = [
    "archive",
    "blog",
    "bootstrap",
    "dark",
    "dark mode",
    "docs",
    "gallery",
    "landing",
    "multilingual",
    "personal",
    "responsive"
]
features = ["search", "flexible", "modular"]
[author]
name = "Razon Yang"
homepage = "https://bdmeter.com"
